name: "Functioanl Test with puppeteer"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    # JST 8:00
    - cron: '0 0 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Install xvfb
        run: apt-get install -y xvfb --no-install-recommends
      - name: Run Jest
        env:
          FIGMA_EMAIL: ${{ secrets.FIGMA_EMAIL }}
          FIGMA_PASSWORD: ${{ secrets.FIGMA_PASSWORD }}
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          DISPLAY: ':99.0'
        run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 & npm test
