name: "E2E Test"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    # JST 6:00
    - cron: '0 21 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: Build chrome extension package
        run: npm run build
      - name: Install xvfb
        run: sudo apt-get install -y xvfb --no-install-recommends
      - name: Run xvfb
        run: Xvfb -ac :99 -screen 0 1920x1080x16 &
      - name: Run Jest
        env:
          FIGMA_EMAIL: ${{ secrets.FIGMA_EMAIL }}
          FIGMA_PASSWORD: ${{ secrets.FIGMA_PASSWORD }}
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          DISPLAY: ':99.0'
        run: npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: figma_jp_chrome_extension
          path: dist
